[project]
name = "sphinx-taskgraph"
version = "0.1.0"
description = "Sphinx extensions to assist with Taskgraph documentation"
readme = "README.md"
authors = [
    { name = "Andrew Halberstadt", email = "ahal@mozilla.com" }
]
dependencies = [
    "sphinx>=7.0.0",
    "voluptuous>=0.12.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
