name: Autoupdate
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.name "Pre-commit automation"
          git config --global user.email "releng+pre-commit-autoupdate@mozilla.com"
      - uses: actions/setup-python@v5
      - run: python -m pip install pre-commit
        shell: bash
      - name: Update files
        run: |
          git checkout -B pre-commit-update
          pre-commit autoupdate -j4
          git add .pre-commit-config.yaml
          git commit -am "Update pre-commit"
          git push -f origin pre-commit-update
      - name: Create PR if necessary
        run: |
          curl -sL \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos${{ github.reository_owner }}/${{ github.repository }}/pulls \
          -d '{"title":"Update pre-commit","body":"","head":"pre-commit-update","base":"${{ github.event.repository.default_branch }}"}'
